spring.config.import=file:.env[.properties]

spring.application.name=Cibot-Chat

server.port=8082

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurar Hibernate para actualizar el esquema de la base de datos automáticamente
spring.jpa.hibernate.ddl-auto=update

# Buenas practicas para JPA
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Habilitar el log de SQL para depuración
spring.jpa.show-sql=true

# Configuración de JWT
security.jwt.secret-key=${JWT_SECRET_KEY}
jwt.expiration-ms=1800000

# Configuración de OpenRouter para Cibot-Chat
openrouter.api.url=https://openrouter.ai/api/v1/chat/completions
openrouter.api.model=openai/gpt-oss-120b:free

# Si no existe, se deja en blanco para evitar caídas catastróficas al compilar.
openrouter.api.key=${OPENROUTER_API_KEY:llave-no-proporcionada}