spring.application.name=Cibot-Chat

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/cibot_chat
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurar Hibernate para actualizar el esquema de la base de datos automáticamente
spring.jpa.hibernate.ddl-auto=update

# Buenas practicas para JPA
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Habilitar el log de SQL para depuración
spring.jpa.show-sql=true

# Configuración de JWT
jwt.secret=clave-super-secreta-de-al-menos-32-caracteres-aqui
jwt.expiration-ms=86400000

# Configuración de CORS
spring.web.cors.allowed-origins=http://localhost:5173