spring.application.name=Cibot-Chat

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/cibot_chat
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurar Hibernate para actualizar el esquema de la base de datos automáticamente
spring.jpa.hibernate.ddl-auto=update

# Buenas practicas para JPA
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Habilitar el log de SQL para depuración
spring.jpa.show-sql=true

# Configuración de JWT
security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration-ms=1800000